version: 2
jobs: 
    build: 
        docker: 
            - image: circleci/ruby:2.4.1
        steps: 
            - checkout
            - run: echo "A first hello"
    test_speed: 
        docker: 
            - image: circleci/ruby:2.4.1
        steps: 
            - checkout
            - run: echo "test speed"

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build  # your custom job from your config, that builds your code
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - build
      # On approval of the `hold` job, any successive job that requires the `hold` job will run. 
      # In this case, a user is manually triggering the deploy job.
      - test_speed