name: Lighthouse
on: status
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://sobreplanos-staging.herokuapp.com/
          configPath: './lighthouserc.json'
          runs: 5
          temporaryPublicStorage: true
